### ISSUE TITLE
Typo in IsoEE application 

### ISSUE THREAD

**Issue by artlbv** [bonanomi/Phase2-L1MenuTools#20]
In https://github.com/bonanomi/Phase2-L1MenuTools/blob/main/objectPerformance/src/quality_obj.py#L16

`< 1.5` should be `> 1.5` (too lazy to make a PR now, can do tomorrow)

**Comment by artlbv** [comment]
Also, if I use isolation not in the first test object it does not seem to work (another different bug)

**Comment by bonanomi** [comment]
Thanks for spotting this! Fixed in https://github.com/bonanomi/Phase2-L1MenuTools/commit/f313e0b2ac9423b485690ee7b19dd1b58743991e

**Comment by bonanomi** [comment]
> Also, if I use isolation not in the first test object it does not seem to work (another different bug)

I am checking this now.
I propose to close this issue and open a new one if I can replicate this error.
